import prisma from "@/lib/prisma";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import crypto from "crypto";
import fs from "fs";
import path from "path";

/**
 * Fetch all transactions for a given year.
 */
export async function getAnnualTransactions(userId: string, workspaceId: string | undefined, year: number) {
  const startDate = new Date(year, 0, 1);
  const endDate = new Date(year, 11, 31, 23, 59, 59, 999);

  return prisma.transaction.findMany({
    where: {
      ...(workspaceId ? { workspaceId } : { userId }),
      date: { gte: startDate, lte: endDate },
      type: "expense", // Only expenses matter for deductions
      status: "APPROVED",
      deletedAt: null,
    },
    orderBy: { date: "asc" },
  });
}

/**
 * Generate a PDF report of business deductions and save it to the public directory
 * so it can be downloaded or sent via Telegram.
 */
export async function generateTaxPDF(
  year: number,
  classifications: { id: string; date: string; amount: number; description: string; category: string; type: "business" | "personal" }[]
): Promise<string> {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.text(`Tax Audit Report - ${year}`, 14, 22);

  doc.setFontSize(12);
  doc.text("Generated by BudgetBuddy AI", 14, 32);

  const businessTxs = classifications.filter((c) => c.type === "business");
  const totalDeductions = businessTxs.reduce((sum, tx) => sum + tx.amount, 0);

  doc.text(`Total Potential Deductions: $${totalDeductions.toFixed(2)}`, 14, 42);

  const tableData = businessTxs.map((tx) => [
    tx.date,
    tx.category,
    tx.description,
    `$${tx.amount.toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: 50,
    head: [["Date", "Category", "Description", "Amount"]],
    body: tableData,
  });

  const fileName = `tax-report-${year}-${crypto.randomUUID().slice(0, 8)}.pdf`;
  const publicDir = path.join(process.cwd(), "public", "reports");
  
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  const filePath = path.join(publicDir, fileName);
  fs.writeFileSync(filePath, Buffer.from(doc.output("arraybuffer")));

  // Return the relative URL so it can be sent or downloaded
  return `/reports/${fileName}`;
}
