"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { 
  FileDown, 
  FileSpreadsheet, 
  FileText, 
  Loader2, 
  Download,
  ShieldCheck,
  Zap,
  TrendingDown,
  TrendingUp,
  CreditCard
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { mkConfig, generateCsv, download } from "export-to-csv";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { PermissionGuard } from "@/components/PermissionGuard";

export function WorkspaceExport({ workspaceId, workspaceName, currency }: { 
    workspaceId: string, 
    workspaceName: string,
    currency: string 
}) {
  const [isExportingCSV, setIsExportingCSV] = useState(false);
  const [isExportingPDF, setIsExportingPDF] = useState(false);

  const fetchExportData = async () => {
    const res = await fetch(`/api/transactions/search?workspaceId=${workspaceId}`);
    if (!res.ok) throw new Error("Failed to fetch data");
    return res.json();
  };

  const handleCSVExport = async () => {
    setIsExportingCSV(true);
    try {
      const data = await fetchExportData();
      
      const csvConfig = mkConfig({
        fieldSeparator: ",",
        decimalSeparator: ".",
        useKeysAsHeaders: true,
        filename: `${workspaceName}_Export_${format(new Date(), "yyyy-MM-dd")}`,
      });

      // Transform data for CSV
      const exportData = data.map((t: any) => ({
        Date: format(new Date(t.date), "yyyy-MM-dd"),
        Description: t.description,
        Category: t.category,
        Type: t.type,
        Amount: t.amount,
        Currency: currency,
        User: t.userId,
        Status: t.status || "Approved"
      }));

      const csv = generateCsv(csvConfig)(exportData);
      download(csvConfig)(csv);
      toast.success("CSV Export generated successfully!");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate CSV export");
    } finally {
      setIsExportingCSV(false);
    }
  };

  const handlePDFExport = async () => {
    setIsExportingPDF(true);
    try {
      const data = await fetchExportData();
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(22);
      doc.setTextColor(16, 185, 129); // Emerald
      doc.text("BudgetBuddy Professional Report", 14, 22);
      
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Workspace: ${workspaceName}`, 14, 30);
      doc.text(`Generated on: ${format(new Date(), "PPP HH:mm")}`, 14, 35);
      doc.text(`Total Records: ${data.length}`, 14, 40);

      // Summary Table Logic
      const totals = data.reduce((acc: any, t: any) => {
        if (t.type === "income") acc.income += t.amount;
        if (t.type === "expense") acc.expense += t.amount;
        return acc;
      }, { income: 0, expense: 0 });

      autoTable(doc, {
        startY: 50,
        head: [["Summary", "Amount"]],
        body: [
          ["Total Income", `${currency} ${totals.income.toLocaleString()}`],
          ["Total Expenses", `${currency} ${totals.expense.toLocaleString()}`],
          ["Net Flow", `${currency} ${(totals.income - totals.expense).toLocaleString()}`],
        ],
        theme: "striped",
        headStyles: { fillColor: [16, 185, 129] },
      });

      autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 15,
        head: [["Date", "Description", "Category", "Type", "Amount"]],
        body: data.map((t: any) => [
          format(new Date(t.date), "MMM d, yyyy"),
          t.description,
          t.category,
          t.type.toUpperCase(),
          `${currency} ${t.amount.toLocaleString()}`
        ]),
        columnStyles: {
            4: { halign: 'right' }
        },
        headStyles: { fillColor: [30, 41, 59] }, // Slate-800
      });

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width / 2, doc.internal.pageSize.height - 10, { align: 'center' });
        doc.text("Generated by BudgetBuddy Pro", 14, doc.internal.pageSize.height - 10);
      }

      doc.save(`${workspaceName}_Tax_Report_${format(new Date(), "yyyy_MM")}.pdf`);
      toast.success("Professional PDF Report generated!");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate PDF report");
    } finally {
      setIsExportingPDF(false);
    }
  };

  return (
    <PermissionGuard allowedRoles={["ADMIN"]}>
      <Card className="border-primary/20 shadow-xl bg-gradient-to-br from-card to-primary/5">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="space-y-1">
              <CardTitle className="flex items-center gap-2 text-primary">
                <FileDown className="w-5 h-5" />
                Workspace Export
              </CardTitle>
              <CardDescription>
                Export your workspace data for tax, accounting, or record keeping.
              </CardDescription>
            </div>
            <div className="p-2 bg-primary/10 rounded-full">
                <Zap className="w-5 h-5 text-primary" />
            </div>
          </div>
        </CardHeader>
        <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="group relative flex flex-col items-center justify-center p-8 rounded-2xl border-2 border-dashed border-primary/20 bg-background/50 hover:bg-primary/5 transition-all cursor-pointer"
               onClick={handleCSVExport}>
            <div className="p-4 rounded-full bg-blue-500/10 text-blue-500 mb-4 group-hover:scale-110 transition-transform">
              <FileSpreadsheet className="w-8 h-8" />
            </div>
            <h3 className="font-bold text-lg">Detailed CSV</h3>
            <p className="text-sm text-muted-foreground text-center mt-2 max-w-[200px]">
              Raw transaction data formatted for Excel or Google Sheets.
            </p>
            <Button 
                variant="link" 
                className="mt-4 text-blue-500"
                disabled={isExportingCSV}
            >
              {isExportingCSV ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Download className="w-4 h-4 mr-2" />}
              {isExportingCSV ? "Generating..." : "Download CSV"}
            </Button>
          </div>

          <div className="group relative flex flex-col items-center justify-center p-8 rounded-2xl border-2 border-dashed border-primary/20 bg-background/50 hover:bg-emerald-500/5 transition-all cursor-pointer"
               onClick={handlePDFExport}>
            <div className="p-4 rounded-full bg-emerald-500/10 text-emerald-500 mb-4 group-hover:scale-110 transition-transform">
              <FileText className="w-8 h-8" />
            </div>
            <h3 className="font-bold text-lg">Professional PDF</h3>
            <p className="text-sm text-muted-foreground text-center mt-2 max-w-[200px]">
              Branded reports with summaries perfect for taxes or reimbursements.
            </p>
            <Button 
                variant="link" 
                className="mt-4 text-emerald-500"
                disabled={isExportingPDF}
            >
              {isExportingPDF ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <ShieldCheck className="w-4 h-4 mr-2" />}
              {isExportingPDF ? "Generating..." : "Generate PDF"}
            </Button>
          </div>
        </CardContent>
      </Card>
    </PermissionGuard>
  );
}
